package main

const dashboardHTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Anvil Resilience Lab</title>
<style>
:root{color-scheme:dark;--bg:#0a0c10;--panel:#12161d;--line:#29313d;--muted:#8b97a8;--text:#eef3f8;--green:#51e29b;--amber:#ffc857;--red:#ff667a;--blue:#71b7ff}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#172130 0,transparent 34%),var(--bg);color:var(--text);font:14px/1.45 ui-monospace,SFMono-Regular,Consolas,monospace}header{display:flex;align-items:center;justify-content:space-between;padding:22px 28px;border-bottom:1px solid var(--line);background:#0a0c10d9;position:sticky;top:0;z-index:2;backdrop-filter:blur(12px)}h1{font-size:20px;letter-spacing:.16em;text-transform:uppercase;margin:0}.tagline{color:var(--muted);font-size:12px}.live{display:flex;align-items:center;gap:8px;color:var(--green)}.dot{width:9px;height:9px;border-radius:50%;background:currentColor;box-shadow:0 0 16px currentColor}.offline{color:var(--red)}main{padding:24px 28px 40px;max-width:1500px;margin:auto}.grid{display:grid;grid-template-columns:repeat(6,minmax(130px,1fr));gap:12px}.card,.section{background:linear-gradient(145deg,#151a22,#0f1319);border:1px solid var(--line);border-radius:10px;box-shadow:0 12px 30px #0003}.card{padding:15px}.label{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.09em}.value{font-size:25px;font-weight:700;margin-top:5px}.section{padding:18px;margin-top:16px}.section h2{font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:var(--muted);margin:0 0 14px}.backends{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.backend{padding:14px;border:1px solid var(--line);border-left:4px solid var(--green);border-radius:7px;background:#0b0f14}.backend.open,.backend.unhealthy{border-left-color:var(--red)}.backend.half-open{border-left-color:var(--amber)}.backend strong{display:flex;justify-content:space-between}.pill{font-size:10px;padding:2px 7px;border:1px solid currentColor;border-radius:99px}.meta{margin-top:9px;color:var(--muted);display:grid;grid-template-columns:1fr 1fr;gap:4px}.timeline{max-height:390px;overflow:auto}.event{display:grid;grid-template-columns:70px 170px 1fr 100px;gap:12px;padding:8px 4px;border-top:1px solid #202732;align-items:start}.event:first-child{border-top:0}.seq{color:var(--blue)}.kind{color:var(--amber)}.reason{color:var(--muted);overflow-wrap:anywhere}.status{text-align:right}.ok{color:var(--green)}.bad{color:var(--red)}footer{color:var(--muted);font-size:11px;margin-top:16px;text-align:right}@media(max-width:950px){.grid{grid-template-columns:repeat(3,1fr)}.event{grid-template-columns:60px 1fr}.event .reason,.event .status{grid-column:2}}@media(max-width:560px){header,main{padding-left:14px;padding-right:14px}.grid{grid-template-columns:repeat(2,1fr)}.tagline{display:none}}
</style>
</head>
<body>
<header><div><h1>ANVIL</h1><div class="tagline">Break the backend. Keep the edge. Explain every decision.</div></div><div id="stream" class="live"><span class="dot"></span><span>LIVE</span></div></header>
<main>
<div class="grid">
<div class="card"><div class="label">Request rate</div><div class="value" id="rate">0.0/s</div></div>
<div class="card"><div class="label">Completed</div><div class="value" id="completed">0</div></div>
<div class="card"><div class="label">Success</div><div class="value" id="success">0%</div></div>
<div class="card"><div class="label">p50 estimate</div><div class="value" id="p50">0 ms</div></div>
<div class="card"><div class="label">p95 estimate</div><div class="value" id="p95">0 ms</div></div>
<div class="card"><div class="label">p99 estimate</div><div class="value" id="p99">0 ms</div></div>
</div>
<section class="section"><h2>Backend topology</h2><div id="backends" class="backends"><div class="label">Waiting for backend state…</div></div></section>
<section class="section"><h2>Decision timeline</h2><div id="timeline" class="timeline"></div></section>
<footer><span id="runtime">runtime pending</span> · histogram values are upper-bound estimates · <span id="drops">0 observer drops</span></footer>
</main>
<script>
const $=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat().format(n||0),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let previous={total:0,time:Date.now()};
async function refresh(){try{const r=await fetch('/api/metrics',{cache:'no-store'});if(!r.ok)throw Error(r.status);const m=await r.json(),now=Date.now(),seconds=Math.max((now-previous.time)/1000,.001),rate=(m.requests.total-previous.total)/seconds;previous={total:m.requests.total,time:now};$('rate').textContent=rate.toFixed(1)+'/s';$('completed').textContent=fmt(m.requests.completed);$('success').textContent=(m.requests.completed?100*m.requests.successes/m.requests.completed:0).toFixed(1)+'%';$('p50').textContent=m.latency.p50_ms_estimate.toFixed(1)+' ms';$('p95').textContent=m.latency.p95_ms_estimate.toFixed(1)+' ms';$('p99').textContent=m.latency.p99_ms_estimate.toFixed(1)+' ms';$('drops').textContent=fmt(m.subscribers.dropped_events)+' observer drops';$('runtime').textContent=fmt(m.runtime.goroutines)+' goroutines · '+fmt(m.runtime.heap_objects_bytes)+' heap bytes';renderBackends(m.backends||[])}catch(e){$('stream').className='live offline';$('stream').lastElementChild.textContent='METRICS OFFLINE'}}
function renderBackends(backends){$('backends').innerHTML=backends.length?backends.map(b=>{const cls=!b.healthy?'unhealthy':b.circuit;return '<article class="backend '+esc(cls)+'"><strong><span>'+esc(b.alias)+'</span><span class="pill">'+esc(b.healthy?b.circuit:'unhealthy')+'</span></strong><div class="meta"><span>in-flight</span><span>'+fmt(b.in_flight)+'</span><span>passive failures</span><span>'+fmt(b.passive_failures)+'</span><span>active failures</span><span>'+fmt(b.active_failures)+'</span></div></article>'}).join(''):'<div class="label">No backends configured</div>'}
function addEvent(event){const row=document.createElement('div');row.className='event';const status=event.status?String(event.status):'';row.innerHTML='<span class="seq">#'+fmt(event.sequence)+'</span><span class="kind">'+esc(event.type)+'</span><span class="reason">'+esc([event.backend_alias,event.reason,event.previous_state&&event.previous_state+'→'+event.new_state].filter(Boolean).join(' · '))+'</span><span class="status '+(event.status>=400?'bad':'ok')+'">'+esc(status)+'</span>';const list=$('timeline');list.prepend(row);while(list.children.length>100)list.lastElementChild.remove()}
const stream=new EventSource('/api/events');stream.onopen=()=>{$('stream').className='live';$('stream').lastElementChild.textContent='LIVE'};stream.onerror=()=>{$('stream').className='live offline';$('stream').lastElementChild.textContent='RECONNECTING'};['request_started','backend_selected','attempt_failed','retry_scheduled','request_completed','circuit_transition','health_transition'].forEach(type=>stream.addEventListener(type,e=>{try{addEvent(JSON.parse(e.data))}catch(_){}}));stream.addEventListener('gap',e=>{const d=JSON.parse(e.data);addEvent({sequence:d.oldest_sequence,type:'replay_gap',reason:'events before retained window were dropped'})});refresh();setInterval(refresh,1000);
</script>
</body>
</html>`
